spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    username: testdb
    password: testdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace



