spring:
  spring:
    datasource:
      url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9090